## Bow, Machine learning algorithms

1. Text pre-processing
2. Train-Test split (Prevents data leakage if you do train-test split before your model implementation as our test data should not be trained, it is for testing purpose only)
3. BoW/TFIDF implementation
4. Train your models

In [1]:
import pandas as pd
messages = pd.read_csv('spam.csv', sep=',', encoding='ISO-8859-1')

In [2]:
messages

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [3]:
messages = messages[['v1', 'v2']]
messages.columns = ['label', 'message']

In [4]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
import re
import nltk

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [7]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-z/^A-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p/day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [9]:
# Considering the values of Ham only
y = pd.get_dummies(messages['label'])
y = y.iloc[:, 0].values

In [10]:
y

array([1, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [11]:
# Train Test Spilt
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

In [12]:
y_train

array([1, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [13]:
X_train

['dizzamn aight ask suitem get back',
 'how champ leav glasgow',
 'free ring tone text poli everi week get new tone yr /wk',
 'valentin game send di msg ur friend answer r someon realli love u que colour suit best rpli',
 'thing chang sentenc want concentr educ career im leav',
 'stop howev suggest stay someon abl give or everi stool',
 'gonna let know co come bak holiday day come get text number',
 'hi babe jordan r u im home abroad lone text back u wanna chat xxsp visionsm com text stop stopcost p',
 'sorri cant take call right happen r waxsto wat want come ill get medic insur abl deliv basic care current shop right medic insur give til friday morn that see major person guid right insur',
 'meet lunch la',
 'littl darl far week need coffe run tomo believ time week alreadi',
 'r home come within min',
 'k text way',
 'enjoy semest take care brother',
 'k special',
 'come around lt decim gt pm vikki otsid nw il come tht time',
 'jordan got vote last nite',
 'dont shall buy one dear',
 

In [14]:
len(X_train), len(y_train)

(4457, 4457)

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

## Creating Bag of Words

In [16]:
#  independent features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [17]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float = lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0

In [18]:
cv.vocabulary_

{'aight': 37,
 'ask': 104,
 'get': 779,
 'back': 141,
 'get back': 780,
 'how': 978,
 'leav': 1138,
 'free': 725,
 'ring': 1763,
 'tone': 2164,
 'text': 2093,
 'poli': 1609,
 'everi': 635,
 'week': 2367,
 'new': 1422,
 'yr': 2495,
 'wk': 2419,
 'everi week': 637,
 'new tone': 1426,
 'valentin': 2287,
 'game': 766,
 'send': 1842,
 'di': 521,
 'msg': 1378,
 'ur': 2255,
 'friend': 745,
 'answer': 70,
 'someon': 1932,
 'realli': 1708,
 'love': 1210,
 'colour': 389,
 'suit': 2029,
 'best': 173,
 'rpli': 1781,
 'send di': 1843,
 'ur friend': 2260,
 'thing': 2112,
 'chang': 322,
 'want': 2334,
 'concentr': 412,
 'career': 300,
 'im': 1006,
 'stop': 1997,
 'howev': 979,
 'suggest': 2028,
 'stay': 1989,
 'abl': 3,
 'give': 796,
 'gonna': 826,
 'let': 1150,
 'know': 1086,
 'co': 372,
 'come': 394,
 'bak': 148,
 'holiday': 951,
 'day': 490,
 'number': 1465,
 'let know': 1151,
 'come get': 396,
 'hi': 931,
 'babe': 137,
 'jordan': 1057,
 'home': 956,
 'lone': 1190,
 'wanna': 2333,
 'chat': 331,
 '

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
spam_detection = MultinomialNB()

In [21]:
# Trainig our data on X_tain and y_train
spam_detection.fit(X_train, y_train)

MultinomialNB()

In [22]:
# Storing the prediction fot X_test in y_pred for further analysis
y_pred = spam_detection.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score, classification_report

In [25]:
accuracy_score(y_test, y_pred)

0.9901345291479821

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96       151
           1       0.99      0.99      0.99       964

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

