In [1]:
import pandas as pd
import numpy as np

In [2]:
reviews = pd.read_csv('all_kindle_review.csv')

In [3]:
reviews

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [ ]:
reviews[['reviewText','rating']]

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [5]:
reviews = reviews[['reviewText','rating']]
reviews.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [6]:
reviews.shape

(12000, 2)

In [7]:
# Missing values
reviews.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [8]:
reviews['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [9]:
reviews['rating'].value_counts()

5    3000
4    3000
3    2000
2    2000
1    2000
Name: rating, dtype: int64

### Preprocessing and data cleaning

In [10]:
#  Considering the ratings below 3 as negative and above 3 as positive, so converting positive review as 1 and negative reviews as 0
reviews['rating'] = reviews['rating'].apply(lambda x:0 if x<3 else 1)

C:\Users\91780\AppData\Local\Temp\ipykernel_14992\220056837.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['rating'] = reviews['rating'].apply(lambda x:0 if x<3 else 1)


In [11]:
reviews

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       1
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       1
3      Aggie is Angela Lansbury who carries pocketboo...       1
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [12]:
reviews['rating'].value_counts()

1    8000
0    4000
Name: rating, dtype: int64

In [13]:
# Lowering all the cases
reviews['reviewText'] = reviews['reviewText'].str.lower()

C:\Users\91780\AppData\Local\Temp\ipykernel_14992\3850680679.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['reviewText'] = reviews['reviewText'].str.lower()


In [14]:
reviews.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [15]:
import re
import nltk
from nltk.corpus import stopwords

In [16]:
%pip install beautifulsoup4

Note: you may need to restart the kernel to use updated packages.


In [17]:
from bs4 import BeautifulSoup

In [18]:
%pip install lxml

Note: you may need to restart the kernel to use updated packages.


In [19]:
# Removing special characters
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ', x))

# Removing stopwords
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:" ".join([word for word in x.split() if word not in stopwords.words('english')]))

## Remove url 
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))

## Remove html tags
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

## Remove any additional spaces
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\91780\AppData\Local\Temp\ipykernel_14992\4288448471.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ', x))
C:\Users\91780\AppData\Local\Temp\ipykernel_14992\4288448471.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:" ".join([word for word in x.split() if word not in stopwords.words('english')]))
C:\Users\91780\AppData\Local\Temp

In [20]:
reviews.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four books expecting 34 con...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [21]:
from nltk.stem import WordNetLemmatizer

In [22]:
lemmatizer = WordNetLemmatizer()

In [23]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [24]:
reviews['reviewText'] = reviews['reviewText'].apply(lambda x: lemmatize_words(x))

C:\Users\91780\AppData\Local\Temp\ipykernel_14992\31910346.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['reviewText'] = reviews['reviewText'].apply(lambda x: lemmatize_words(x))


In [25]:
reviews.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting 34 conc...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

### Train Test Split

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(reviews['reviewText'], reviews['rating'], test_size = 0.20)

### Word embedding techniques

In [28]:
X_train

9241     purchased book author glad coudn get past 1st ...
11219    book recommended actually liked looking suspen...
10424    originally going give book 4 star becausegetti...
615      book supposed 34 thriller 34 call murder belov...
1117     pleasantly surprised book loved fact plus size...
                               ...                        
317      one thing could say chase book different one s...
5443     started book mildly entertained though found t...
515      course generally knew story actually never rea...
1154     discovered jennifer crusie late really enjoy b...
2315     enjoyed story loved character story little cho...
Name: reviewText, Length: 9600, dtype: object

In [29]:
# BoW implemenatation
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [30]:
# TF-IDF implementation
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [31]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### ML Algorithms

In [33]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow, y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf, y_train)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [35]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [36]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [37]:
confusion_matrix(y_test, y_pred_bow)

array([[550, 262],
       [731, 857]], dtype=int64)

In [38]:
print("BoW accuracy: ", accuracy_score(y_test, y_pred_bow))

BoW accuracy:  0.58625


In [39]:
confusion_matrix(y_test, y_pred_tfidf)

array([[536, 276],
       [726, 862]], dtype=int64)

In [40]:
print("TFIDF accuracy: ", accuracy_score(y_test, y_pred_tfidf))

TFIDF accuracy:  0.5825


### Word2Vec Implementation

In [41]:
reviews

reviewText  rating
0      jace rankin may short nothing mess man hauled ...       1
1      great short read want put read one sitting sex...       1
2      start saying first four book expecting 34 conc...       1
3      aggie angela lansbury carry pocketbook instead...       1
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire jena ian another vampi...       1
11996  read seven book series apocalyptic adventure o...       1
11997  book really cuppa situation man capturing woma...       1
11998  tried use charge kindle even register charging...       0
11999  taking instruction look often hidden world sex...       1

[12000 rows x 2 columns]

In [42]:
reviews['reviewText']

0        jace rankin may short nothing mess man hauled ...
1        great short read want put read one sitting sex...
2        start saying first four book expecting 34 conc...
3        aggie angela lansbury carry pocketbook instead...
4        expect type book library pleased find price right
                               ...                        
11995    valentine cupid vampire jena ian another vampi...
11996    read seven book series apocalyptic adventure o...
11997    book really cuppa situation man capturing woma...
11998    tried use charge kindle even register charging...
11999    taking instruction look often hidden world sex...
Name: reviewText, Length: 12000, dtype: object

In [43]:
corpus = reviews['reviewText']

In [44]:
corpus

0        jace rankin may short nothing mess man hauled ...
1        great short read want put read one sitting sex...
2        start saying first four book expecting 34 conc...
3        aggie angela lansbury carry pocketbook instead...
4        expect type book library pleased find price right
                               ...                        
11995    valentine cupid vampire jena ian another vampi...
11996    read seven book series apocalyptic adventure o...
11997    book really cuppa situation man capturing woma...
11998    tried use charge kindle even register charging...
11999    taking instruction look often hidden world sex...
Name: reviewText, Length: 12000, dtype: object

In [45]:
import gensim

In [46]:
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

In [47]:
# words = []
# for sent in corpus:
#     sent_token = sent_tokenize(sent)
#     for sent in sent_token:
#         words.append(simple_preprocess(sent))

words = [review.split() for review in corpus]

In [48]:
lemmatized_word = []
for review in words:
    lemmatized_review = [lemmatizer.lemmatize(word, pos="v") for word in review]
    lemmatized_word.append(lemmatized_review)

In [49]:
lemmatized_word

[['jace',
  'rankin',
  'may',
  'short',
  'nothing',
  'mess',
  'man',
  'haul',
  'saloon',
  'undertaker',
  'know',
  'famous',
  'bounty',
  'hunter',
  'oregon',
  '1890s',
  'shoot',
  'man',
  'saloon',
  'finish',
  'year',
  'long',
  'quest',
  'avenge',
  'sister',
  'murder',
  'try',
  'figure',
  'next',
  'snotty',
  'nose',
  'farm',
  'boy',
  'rescue',
  'gang',
  'bully',
  'offer',
  'money',
  'kill',
  'man',
  'force',
  'ranch',
  'reluctantly',
  'agree',
  'bring',
  'man',
  'justice',
  'kill',
  'outright',
  'first',
  'need',
  'tell',
  'sister',
  'widower',
  'news',
  'kyla',
  'kyle',
  'springer',
  'bailey',
  'rid',
  'trail',
  'sleep',
  'grind',
  'past',
  'month',
  'try',
  'find',
  'jace',
  'want',
  'revenge',
  'man',
  'kill',
  'husband',
  'take',
  'ranch',
  'amongst',
  'crime',
  'keen',
  'detour',
  'jace',
  'want',
  'take',
  'realize',
  'option',
  'hide',
  'behind',
  'boy',
  'persona',
  'best',
  'try',
  'keep',
 

In [50]:
w2v_model = gensim.models.Word2Vec(lemmatized_word, epochs=1000, vector_size=100)

In [51]:
w2v_model.wv.index_to_key

['book',
 'story',
 'read',
 'like',
 'one',
 'character',
 'get',
 'love',
 'good',
 'would',
 'really',
 'time',
 'make',
 'author',
 'think',
 'write',
 'go',
 'find',
 'want',
 'know',
 'series',
 'well',
 'end',
 'enjoy',
 'much',
 'first',
 'even',
 'give',
 'short',
 'way',
 'take',
 'great',
 'could',
 'sex',
 'little',
 'say',
 'interest',
 'two',
 'thing',
 'see',
 'plot',
 'come',
 'feel',
 'romance',
 'also',
 'keep',
 'work',
 'look',
 'life',
 'start',
 'seem',
 'scene',
 'never',
 'need',
 'woman',
 'review',
 'kindle',
 'bite',
 'try',
 'many',
 'lot',
 'year',
 'novel',
 'another',
 'better',
 'man',
 'star',
 'hot',
 'tell',
 'still',
 'back',
 'though',
 'reader',
 'enough',
 'happen',
 'recommend',
 'people',
 'friend',
 'part',
 'page',
 'something',
 'world',
 'leave',
 'free',
 'bad',
 '34',
 'new',
 'relationship',
 'use',
 'together',
 'put',
 'next',
 'turn',
 'felt',
 'buy',
 'finish',
 'best',
 'begin',
 'word',
 'guy',
 'main',
 'long',
 'however',
 'line',

In [52]:
w2v_model.corpus_count

12000

In [56]:
w2v_model.wv.similar_by_word('good')

[('great', 0.7138372659683228),
 ('decent', 0.6351151466369629),
 ('enjoy', 0.5446795225143433),
 ('like', 0.5430467128753662),
 ('interest', 0.4890233874320984),
 ('ok', 0.47914743423461914),
 ('nice', 0.47626739740371704),
 ('okay', 0.4453808069229126),
 ('bad', 0.43999508023262024),
 ('excellent', 0.43271976709365845)]

In [57]:
w2v_model.wv['good'].shape

(100,)

In [59]:
import numpy as np
def avg_w2v(doc):
    return np.mean([w2v_model.wv[word] for word in doc if word in w2v_model.wv.key_to_index], axis=0)

In [60]:
from tqdm import tqdm
X_w2v = []
for i in tqdm(range(len(lemmatized_word))):
    X_w2v.append(avg_w2v(lemmatized_word[i]))

100%|██████████| 12000/12000 [00:01<00:00, 11961.33it/s]


In [61]:
X_w2v

[array([ 0.22668211,  0.1921107 ,  0.02371861, -0.09259292,  0.32986397,
         0.43538487,  0.01583393,  0.2981183 , -0.05051056,  0.41947585,
        -0.0448213 ,  0.2562146 ,  0.00937909, -0.17601696,  0.10993791,
        -0.24870071, -0.6229438 ,  0.41576305,  0.07527498, -0.22906807,
        -0.21161345, -0.04736393,  0.15431368,  0.03132885, -0.12434467,
        -0.7771935 ,  0.11280011, -0.05740936, -0.39504924,  0.14302602,
        -0.41967335,  0.74128234, -0.37165362,  0.2405007 ,  0.49831665,
        -0.00270418, -0.37626296, -0.38684362, -0.21633923, -0.30655915,
         0.4698047 , -0.2615169 ,  0.5694183 , -0.10403202, -0.39803016,
         0.36698756,  0.05878802,  0.08335561,  0.43196884, -0.03905667,
         0.2748201 , -0.5616321 ,  0.03618425,  0.00249916, -0.13286963,
        -0.08364327, -0.3298578 , -0.45773223, -0.32255623, -0.0231324 ,
         0.7606844 ,  0.33109313,  0.07051983, -0.3382257 ,  0.29063556,
         0.44236523, -0.08400217, -0.39426014, -0.3

In [62]:
len(X_w2v)

12000

In [63]:
X_new_w2v = np.array(X_w2v)
X_new_w2v.shape

(12000, 100)

In [65]:
X_new_w2v[0].shape

(100,)

In [78]:
y = reviews['rating'].to_numpy()

In [79]:
y

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [80]:
y.shape

(12000,)

In [71]:
import pandas as pd
df = pd.DataFrame(X_new_w2v)

In [72]:
df.head()

0         1         2         3         4         5         6   \
0  0.226682  0.192111  0.023719 -0.092593  0.329864  0.435385  0.015834   
1  1.236200  0.405478  0.303471  0.783098  1.056463  0.184599 -0.108668   
2  0.234932 -0.356564  0.275469 -0.087540  0.320328  0.226895  0.596040   
3  0.493954 -0.414664 -0.203845 -0.909183 -0.241019 -0.340793 -0.146711   
4  0.404354 -0.296520 -0.012441  0.772128  1.389205  0.840352 -0.425539   

         7         8         9   ...        90        91        92        93  \
0  0.298118 -0.050511  0.419476  ...  0.180274  0.072962  0.073928  0.428566   
1 -0.713509 -0.326496 -0.438278  ... -0.478068  0.591200  0.251427 -1.264639   
2 -0.374072 -0.278117  0.027351  ... -0.385571  0.278467  0.029507 -0.343489   
3 -0.557415 -0.913075 -0.462066  ...  0.315786  0.200909 -0.598830 -0.683284   
4 -1.756218 -0.785393  0.569133  ... -1.717606  0.096869 -1.137389  0.178888   

         94        95        96        97        98        99  
0 -0.404636  0.164603  0.409259 -0.045592 -0.282887  0.322278  
1 -0.134347 -0.328283 -1.154817 -0.533344  0.351352 -0.398229  
2  0.154374  0.132917 -0.400199  0.083074  0.489577  0.047535  
3 -0.963264 -0.542435 -0.188191 -0.718603  0.790524 -0.098147  
4 -0.130360 -1.000145 -0.692262 -0.458515  0.143277 -0.758560  

[5 rows x 100 columns]

In [81]:
df['Output'] = y

In [82]:
df.head()

0         1         2         3         4         5         6  \
0  0.226682  0.192111  0.023719 -0.092593  0.329864  0.435385  0.015834   
1  1.236200  0.405478  0.303471  0.783098  1.056463  0.184599 -0.108668   
2  0.234932 -0.356564  0.275469 -0.087540  0.320328  0.226895  0.596040   
3  0.493954 -0.414664 -0.203845 -0.909183 -0.241019 -0.340793 -0.146711   
4  0.404354 -0.296520 -0.012441  0.772128  1.389205  0.840352 -0.425539   

          7         8         9  ...        91        92        93        94  \
0  0.298118 -0.050511  0.419476  ...  0.072962  0.073928  0.428566 -0.404636   
1 -0.713509 -0.326496 -0.438278  ...  0.591200  0.251427 -1.264639 -0.134347   
2 -0.374072 -0.278117  0.027351  ...  0.278467  0.029507 -0.343489  0.154374   
3 -0.557415 -0.913075 -0.462066  ...  0.200909 -0.598830 -0.683284 -0.963264   
4 -1.756218 -0.785393  0.569133  ...  0.096869 -1.137389  0.178888 -0.130360   

         95        96        97        98        99  Output  
0  0.164603  0.409259 -0.045592 -0.282887  0.322278       1  
1 -0.328283 -1.154817 -0.533344  0.351352 -0.398229       1  
2  0.132917 -0.400199  0.083074  0.489577  0.047535       1  
3 -0.542435 -0.188191 -0.718603  0.790524 -0.098147       1  
4 -1.000145 -0.692262 -0.458515  0.143277 -0.758560       1  

[5 rows x 101 columns]

In [84]:
X_new_w2v = df

In [85]:
X_new_w2v.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
Output    0
Length: 101, dtype: int64

In [86]:
y = df['Output']

In [87]:
X_train_w2v, X_test_w2v, y_train_w2v, y_test_w2v = train_test_split(X_new_w2v, y, test_size=0.20)

In [88]:
X_train_w2v.head()

0         1         2         3         4         5         6  \
464    1.015381  0.649671 -0.143373  1.763363  1.579368 -0.235617 -0.332858   
6556   0.657586 -0.032641  0.384192  0.766415  1.332799 -0.958903 -1.374222   
10076  0.550774  0.890652  0.117441 -0.254929 -0.002209  0.843216  0.323999   
2345   0.411900  0.057136  0.677475  0.943747  0.962504 -0.106700 -0.024159   
2148   0.191022 -0.053476  0.523053  0.453298  0.596235 -0.199534 -0.475668   

              7         8         9  ...        91        92        93  \
464   -0.793892 -1.952034 -0.433502  ...  1.349029  0.620496 -1.293951   
6556  -0.896966  0.236738 -0.107251  ...  1.352875  0.308785 -0.271981   
10076 -0.115686  0.760697  0.744629  ...  0.235586  0.215356 -0.491107   
2345  -1.640381  0.350576 -0.602401  ...  1.133651 -1.246198  0.156887   
2148  -0.640169  0.161213  0.469115  ...  0.824731 -0.155871 -0.131762   

             94        95        96        97        98        99  Output  
464   -0.161267 -0.822051 -0.235454  0.431239  0.706269 -1.085156       1  
6556  -1.215959 -0.473870  0.391842  0.328422  0.372902 -0.365939       0  
10076 -0.953087  0.497643 -0.683362  0.063967 -0.326595  0.813420       1  
2345   0.246630 -0.442245 -0.704512  0.508652 -0.168663 -0.366898       1  
2148  -0.420190 -0.171666  0.070261  0.307770 -0.651996 -0.687356       1  

[5 rows x 101 columns]

In [89]:
y_train_w2v

464      1
6556     0
10076    1
2345     1
2148     1
        ..
1966     0
1701     1
7443     1
9903     0
9401     0
Name: Output, Length: 9600, dtype: int64

In [90]:
nb_model_w2v = GaussianNB().fit(X_train_w2v, y_train_w2v)

c:\Users\91780\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [92]:
y_pred_w2v = nb_model_w2v.predict(X_test_w2v)

c:\Users\91780\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [93]:
print("W2V accuracy: ", accuracy_score(y_test_w2v, y_pred_w2v))

W2V accuracy:  1.0
