In [1]:
import pandas as pd
import numpy as np

In [2]:
reviews = pd.read_csv('all_kindle_review.csv')

In [3]:
reviews

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0                 0       11539  B0033UV8HI  [8, 10]       3   
1                 1        5957  B002HJV4DE   [1, 1]       5   
2                 2        9146  B002ZG96I4   [0, 0]       3   
3                 3        7038  B002QHWOEU   [1, 3]       3   
4                 4        1776  B001A06VJ8   [0, 1]       4   
...             ...         ...         ...      ...     ...   
11995         11995        2183  B001DUGORO   [0, 0]       4   
11996         11996        6272  B002JCSFSQ   [2, 2]       5   
11997         11997       12483  B0035N1V7K   [0, 1]       3   
11998         11998        3640  B001W1XT40   [1, 2]       1   
11999         11999       11398  B003370JUS   [5, 6]       3   

                                              reviewText   reviewTime  \
0      Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1      Great short read.  I didn't want to put it dow...   10 8, 2013   
2      I'll start by saying this is the first of four...  04 11, 2014   
3      Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4      I did not expect this type of book to be in li...  12 31, 2012   
...                                                  ...          ...   
11995  Valentine cupid is a vampire- Jena and Ian ano...  02 28, 2014   
11996  I have read all seven books in this series. Ap...  05 16, 2011   
11997  This book really just wasn't my cuppa.  The si...  07 26, 2013   
11998  tried to use it to charge my kindle, it didn't...  09 17, 2013   
11999  Taking Instruction is a look into the often hi...   07 5, 2012   

           reviewerID                   reviewerName  \
0      A3HHXRELK8BHQG                         Ridley   
1      A2RGNZ0TRF578I                   Holly Butler   
2      A3S0H2HV6U1I7F                        Merissa   
3       AC4OQW3GZ919J                     Cleargrace   
4      A3C9V987IQHOQD                       Rjostler   
...               ...                            ...   
11995  A1OKS5Q1HD8WQC                  lisa jon jung   
11996   AQRSPXLNEQAMA                        TerryLP   
11997  A2T5QLT5VXOJAK                        hwilson   
11998  A28MHD2DDY6DXB  Allison A. Slater "Gryphon50"   
11999  A3JUXLB4K9ZXCC                      Dafna Yee   

                                                 summary  unixReviewTime  
0                               Entertaining But Average      1283385600  
1                                Terrific menage scenes!      1381190400  
2                                       Snapdragon Alley      1397174400  
3                                 very light murder cozy      1404518400  
4                                                   Book      1356912000  
...                                                  ...             ...  
11995                                               jena      1393545600  
11996                                Peacekeepers Series      1305504000  
11997                                    a little creepy      1374796800  
11998                                        didn't work      1379376000  
11999  If you like BDSM with a touch of romance, this...      1341446400  

[12000 rows x 11 columns]

In [4]:
reviews[['reviewText','rating']]

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [5]:
reviews = reviews[['reviewText','rating']]
reviews.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [6]:
reviews.shape

(12000, 2)

In [7]:
# Missing values
reviews.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [8]:
reviews['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [9]:
reviews['rating'].value_counts()

5    3000
4    3000
3    2000
2    2000
1    2000
Name: rating, dtype: int64

### Preprocessing and data cleaning

In [10]:
#  Considering the ratings below 3 as negative and above 3 as positive, so converting positive review as 1 and negative reviews as 0
reviews['rating'] = reviews['rating'].apply(lambda x:0 if x<3 else 1)

C:\Users\91780\AppData\Local\Temp\ipykernel_18544\220056837.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['rating'] = reviews['rating'].apply(lambda x:0 if x<3 else 1)


In [11]:
reviews

reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       1
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       1
3      Aggie is Angela Lansbury who carries pocketboo...       1
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [12]:
reviews['rating'].value_counts()

1    8000
0    4000
Name: rating, dtype: int64

In [13]:
# Lowering all the cases
reviews['reviewText'] = reviews['reviewText'].str.lower()

C:\Users\91780\AppData\Local\Temp\ipykernel_18544\3850680679.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['reviewText'] = reviews['reviewText'].str.lower()


In [14]:
reviews.head()

reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [15]:
import re
import nltk
from nltk.corpus import stopwords

In [16]:
%pip install beautifulsoup4

Note: you may need to restart the kernel to use updated packages.


In [17]:
from bs4 import BeautifulSoup

In [18]:
%pip install lxml

Note: you may need to restart the kernel to use updated packages.


In [19]:
# Removing special characters
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ', x))

# Removing stopwords
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:" ".join([word for word in x.split() if word not in stopwords.words('english')]))

## Remove url 
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))

## Remove html tags
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())

## Remove any additional spaces
reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\91780\AppData\Local\Temp\ipykernel_18544\4288448471.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', ' ', x))
C:\Users\91780\AppData\Local\Temp\ipykernel_18544\4288448471.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews.loc[:, 'reviewText'] = reviews['reviewText'].apply(lambda x:" ".join([word for word in x.split() if word not in stopwords.words('english')]))
C:\Users\91780\AppData\Local\Temp

In [20]:
reviews.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four books expecting 34 con...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [21]:
from nltk.stem import WordNetLemmatizer

In [22]:
lemmatizer = WordNetLemmatizer()

In [24]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [25]:
reviews['reviewText'] = reviews['reviewText'].apply(lambda x: lemmatize_words(x))

C:\Users\91780\AppData\Local\Temp\ipykernel_18544\31910346.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reviews['reviewText'] = reviews['reviewText'].apply(lambda x: lemmatize_words(x))


In [26]:
reviews.head()

reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting 34 conc...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

### Train Test Split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(reviews['reviewText'], reviews['rating'], test_size = 0.20)

### Word embedding techniques

In [40]:
X_train

1628     simply love debbie macomber usually purchase b...
8382     book lelt wanting sexual tension office could ...
382      red better turning long drawn saga know read n...
1308     book actually held together well unapologetic ...
10400    title kind give away fact child become orphan ...
                               ...                        
2991     aside formatting error need place break scene ...
5260     tend shy away book character jump right bed fi...
3008     expecting lot kinky honest publisher descripti...
2589     short sexy story woman find love seeking reven...
877      story hooked beginning skylar kade writes wond...
Name: reviewText, Length: 9600, dtype: object

In [35]:
# BoW implemenatation
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [36]:
# TF-IDF implementation
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [38]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### ML Algorithms

In [42]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow, y_train)
nb_model_tfidf = GaussianNB().fit(X_train_tfidf, y_train)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [45]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [47]:
y_pred_tfidf = nb_model_bow.predict(X_test_tfidf)

In [49]:
confusion_matrix(y_test, y_pred_bow)

array([[534, 255],
       [760, 851]], dtype=int64)

In [48]:
print("BoW accuracy: ", accuracy_score(y_test, y_pred_bow))

BoW accuracy:  0.5770833333333333


In [50]:
confusion_matrix(y_test, y_pred_tfidf)

array([[527, 262],
       [755, 856]], dtype=int64)

In [51]:
print("TFIDF accuracy: ", accuracy_score(y_test, y_pred_tfidf))

TFIDF accuracy:  0.57625
